import type { Level, Pattern } from "./types";

const l1 = (
  slug: string,
  title: string,
  group: string,
  intuition: string,
  whenToUse: string,
  time: string,
  space: string,
  example: string,
): Pattern => ({
  slug,
  title,
  group,
  level: 1,
  ready: true,
  intuition,
  whenToUse,
  complexity: { time, space },
  example,
});

const l2 = (
  slug: string,
  title: string,
  group: string,
  intuition: string,
  whenToUse: string,
  time: string,
  space: string,
  example: string,
): Pattern => ({
  slug,
  title,
  group,
  level: 2,
  ready: true,
  intuition,
  whenToUse,
  complexity: { time, space },
  example,
});

const l3 = (
  slug: string,
  title: string,
  group: string,
  intuition: string,
  whenToUse: string,
  time: string,
  space: string,
  example: string,
): Pattern => ({
  slug,
  title,
  group,
  level: 3,
  ready: true,
  intuition,
  whenToUse,
  complexity: { time, space },
  example,
});

export const levels: Level[] = [
  {
    id: 1,
    title: "Must-Have",
    subtitle: "Clear interviews at 5–8 LPA",
    band: "5–8 LPA",
    warning: "If you skip these, interviews won’t clear.",
    ready: true,
    groups: [
      {
        id: "array-string",
        title: "Array & String Patterns",
        emoji: "01",
        blurb: "Walk arrays with pointers, windows, sums, and maps.",
        patterns: [
          l1(
            "two-pointers",
            "Two Pointers",
            "Array & String",
            "Place two indices and move them based on a condition instead of nested loops. They either walk inward from both ends or chase each other in one direction.",
            "Sorted arrays, palindromes, pair sums, partitioning, merging two lists.",
            "O(n)",
            "O(1)",
            "Find two numbers in a sorted array that add to a target.",
          ),
          l1(
            "sliding-window",
            "Sliding Window (Fixed + Variable)",
            "Array & String",
            "Keep a contiguous segment of the array. Expand the right edge to include data, shrink the left edge when the window breaks a constraint.",
            "Subarray / substring problems: max sum of size k, longest unique substring, smallest window covering a need.",
            "O(n)",
            "O(1) or O(k)",
            "Maximum sum of any subarray of length 3.",
          ),
          l1(
            "prefix-sum",
            "Prefix Sum",
            "Array & String",
            "Precompute running totals so any range sum becomes two lookups: prefix[r] − prefix[l − 1].",
            "Many range-sum queries, equilibrium index, subarray sum equals k (with a map).",
            "O(n) build, O(1) query",
            "O(n)",
            "Answer range sum queries after one pass.",
          ),
          l1(
            "difference-array",
            "Difference Array",
            "Array & String",
            "Encode a range update as +val at L and −val at R+1. A prefix pass materializes the final array.",
            "Many range add/subtract updates, then one final array.",
            "O(n + q)",
            "O(n)",
            "Add +2 to every index from 1 to 3, then reconstruct.",
          ),
          l1(
            "kadane",
            "Kadane’s Algorithm",
            "Array & String",
            "Track the best subarray ending at the current index. Either extend it or start fresh from this element.",
            "Maximum subarray sum (contiguous). Variants: max product, circular kadane.",
            "O(n)",
            "O(1)",
            "Maximum contiguous sum in an array with negatives.",
          ),
          l1(
            "sorting-tricks",
            "Sorting-based tricks",
            "Array & String",
            "Sorting turns unordered data into a line you can scan with two pointers, greedy choices, or adjacent comparisons.",
            "Anagram groups (sort keys), 3-sum, meeting rooms, closest pairs after sort.",
            "O(n log n)",
            "O(1) or O(n)",
            "After sorting, scan for the closest pair of values.",
          ),
          l1(
            "frequency-map",
            "Frequency Map",
            "Array & String",
            "Count how often each value appears, then decide from counts instead of scanning again and again.",
            "Anagrams, majority element, top-k frequent, character budgets in windows.",
            "O(n)",
            "O(k)",
            "Count letters and check if two strings are anagrams.",
          ),
        ],
      },
      {
        id: "binary-search",
        title: "Binary Search Patterns",
        emoji: "02",
        blurb: "Halve the search space on arrays and on answers.",
        patterns: [
          l1(
            "classic-binary-search",
            "Classic Binary Search",
            "Binary Search",
            "On a sorted range, look at the middle. Throw away half that cannot contain the target.",
            "Find an exact value in a sorted array.",
            "O(log n)",
            "O(1)",
            "Search for 13 in a sorted list.",
          ),
          l1(
            "first-last-occurrence",
            "First / Last Occurrence",
            "Binary Search",
            "When duplicates exist, binary search still works — bias mid toward the left for first, toward the right for last.",
            "Lower/upper index of a value, count of a number in a sorted array.",
            "O(log n)",
            "O(1)",
            "Find the first and last index of 2 in [1, 2, 2, 2, 3].",
          ),
          l1(
            "lower-upper-bound",
            "Lower Bound / Upper Bound",
            "Binary Search",
            "Lower bound: first index ≥ x. Upper bound: first index > x. Both are binary searches with a different comparison.",
            "Insert position, counting how many values lie in [L, R].",
            "O(log n)",
            "O(1)",
            "Find where 7 would sit in a sorted array.",
          ),
          l1(
            "binary-search-on-answer",
            "Binary Search on Answer",
            "Binary Search",
            "The array is not sorted — the answer space is. Binary search a candidate value and check if it is feasible.",
            "Minimize max load, Koko eating bananas, split array largest sum, capacity to ship packages.",
            "O(n log A)",
            "O(1)",
            "Minimum eating speed so all bananas finish in H hours.",
          ),
        ],
      },
      {
        id: "hashing",
        title: "Hashing Patterns",
        emoji: "03",
        blurb: "Trade memory for O(1) lookups.",
        patterns: [
          l1(
            "hashmap-lookup",
            "HashMap lookup",
            "Hashing",
            "Store what you have already seen so the next item can ask “have I met my pair?” in constant time.",
            "Two-sum, clone graph, index of previous occurrence.",
            "O(n)",
            "O(n)",
            "Two-sum: for each x, look up target − x.",
          ),
          l1(
            "frequency-counting",
            "Frequency counting",
            "Hashing",
            "Same idea as a frequency map, but the hash table is the star: increment, decrement, and react when a count hits zero or a threshold.",
            "Valid anagram, majority vote, subarrays with k distinct.",
            "O(n)",
            "O(k)",
            "Build a count map while scanning a string.",
          ),
          l1(
            "set-detection",
            "Set-based detection",
            "Hashing",
            "A set answers “have I seen this?” A second insert that fails means a duplicate or a cycle in values.",
            "Contains duplicate, longest consecutive sequence, seen-pair detection.",
            "O(n)",
            "O(n)",
            "Detect the first repeated number.",
          ),
        ],
      },
      {
        id: "linked-list",
        title: "Linked List Patterns",
        emoji: "04",
        blurb: "Rewire pointers carefully — one wrong next breaks the chain.",
        patterns: [
          l1(
            "fast-slow-pointer",
            "Fast & Slow Pointer",
            "Linked List",
            "Slow moves one step, fast moves two. They meet on a cycle; when fast hits null, slow is at the middle.",
            "Middle of the list, cycle detection, palindrome list (slow at mid).",
            "O(n)",
            "O(1)",
            "Find the middle node of a list.",
          ),
          l1(
            "reverse-linked-list",
            "Reverse Linked List",
            "Linked List",
            "Walk the list once. For each node, point next backward, then advance. Three pointers: prev, curr, next.",
            "Reverse whole list or a sublist, palindrome check.",
            "O(n)",
            "O(1)",
            "Reverse 1 → 2 → 3 → 4.",
          ),
          l1(
            "merge-lists",
            "Merge Lists",
            "Linked List",
            "Two sorted lists can be fused by always taking the smaller head, like merge in merge-sort.",
            "Merge two sorted lists, merge k lists (with a heap later).",
            "O(n + m)",
            "O(1)",
            "Merge 1→3→5 with 2→4.",
          ),
          l1(
            "cycle-detection",
            "Cycle Detection",
            "Linked List",
            "Floyd’s tortoise and hare: if there is a loop, fast laps slow. After they meet, reset one to head; they meet at the cycle start.",
            "Detect cycle, find cycle entrance, happy number.",
            "O(n)",
            "O(1)",
            "Show slow and fast meeting inside a loop.",
          ),
        ],
      },
      {
        id: "stack",
        title: "Stack Patterns",
        emoji: "05",
        blurb: "Last in, first out — matches nesting and nearest previous.",
        patterns: [
          l1(
            "valid-parentheses",
            "Valid Parentheses",
            "Stack",
            "Push opening brackets. A closing bracket must match the top. The stack empty at the end means balanced.",
            "Brackets, HTML tags, nested structures.",
            "O(n)",
            "O(n)",
            "Check whether { [ ( ) ] } is valid.",
          ),
          l1(
            "infix-prefix-postfix",
            "Infix / Prefix / Postfix",
            "Stack",
            "Operator precedence plus a stack converts infix (human) into postfix (machine). Prefix is the mirror using a reversed scan.",
            "Expression evaluation, calculator, compiler parsing.",
            "O(n)",
            "O(n)",
            "Convert A + B * C to postfix A B C * +.",
          ),
          l1(
            "next-greater-element",
            "Next Greater / Smaller Element",
            "Stack",
            "Scan right-to-left or left-to-right while popping indices that are smaller than the current value. The stack holds a decreasing (or increasing) candidate list.",
            "NGE, NSE, stock span, daily temperatures.",
            "O(n)",
            "O(n)",
            "For each number, find the next greater to its right.",
          ),
          l1(
            "monotonic-stack",
            "Monotonic Stack",
            "Stack",
            "Keep the stack always increasing or always decreasing. That invariant gives nearest greater/smaller in linear time and is the engine behind histogram rectangles.",
            "Largest rectangle in histogram, trapping rain water, NGE variants.",
            "O(n)",
            "O(n)",
            "Maintain a decreasing stack while scanning heights.",
          ),
        ],
      },
      {
        id: "recursion",
        title: "Recursion Basics",
        emoji: "06",
        blurb: "A function that calls itself — draw the tree, then you understand backtracking.",
        patterns: [
          l1(
            "pick-not-pick",
            "Pick / Not Pick",
            "Recursion",
            "At each index you make a binary choice: include this element, or skip it. The recursion tree has 2^n leaves (all subsets).",
            "Subsets, subset-sum, knapsack decisions, generate combinations.",
            "O(2^n)",
            "O(n) stack",
            "Generate subsets of [1, 2, 3].",
          ),
          l1(
            "recursive-tree",
            "Recursive Tree",
            "Recursion",
            "Every call is a node. Arguments and return values flow down and up. Drawing the tree is how you debug recursion.",
            "Fibonacci (with overlapping), factorial, tree DFS, divide and conquer.",
            "Depends on the tree",
            "O(depth)",
            "Expand fib(4) into fib(3) + fib(2).",
          ),
          l1(
            "backtracking-intro",
            "Backtracking intro",
            "Recursion",
            "Try a choice, recurse, then undo (pop) so the next sibling can try a different choice. The undo is the whole trick.",
            "N-queens, permutations, mazes — full treatment in Level 2.",
            "O(branch^depth)",
            "O(depth)",
            "Place numbers 1 and 2 into two slots, undoing after each try.",
          ),
        ],
      },
    ],
  },
  {
    id: 2,
    title: "Strong Mid",
    subtitle: "Separates average from strong (8–14 LPA)",
    band: "8–14 LPA",
    warning: "These separate average from strong candidates.",
    ready: true,
    groups: [
      {
        id: "trees",
        title: "Tree Patterns",
        emoji: "07",
        blurb: "DFS, BFS, height, diameter, LCA, path sums.",
        patterns: [
          l2(
            "dfs-traversals",
            "DFS (Inorder / Preorder / Postorder)",
            "Trees",
            "Walk the tree recursively. Preorder visits the node first, inorder the left then node, postorder children then node.",
            "Serialization, BST sorted dump (inorder), expression trees, subtree problems.",
            "O(n)",
            "O(h)",
            "Visit a small binary tree in all three orders.",
          ),
          l2(
            "bfs-level-order",
            "BFS / Level Order",
            "Trees",
            "A queue holds the current level. Dequeue a node, enqueue its children. That is level order.",
            "Zigzag levels, right-side view, connect next pointers, shortest root-to-leaf.",
            "O(n)",
            "O(w)",
            "Print nodes level by level using a queue.",
          ),
          l2(
            "height-diameter",
            "Height / Diameter",
            "Trees",
            "Height is 1 + max child height. Diameter is the longest path between any two nodes — often through a root of some subtree.",
            "Balance checks, network diameter, tree DP on paths.",
            "O(n)",
            "O(h)",
            "Compute height bottom-up and track the best left+right path.",
          ),
          l2(
            "balanced-tree",
            "Balanced Tree",
            "Trees",
            "A tree is height-balanced if every node’s subtrees differ in height by at most 1. Return height or −1 as a failure flag.",
            "Validate AVL-style balance, convert sorted array to balanced BST.",
            "O(n)",
            "O(h)",
            "Post-order: if |left − right| > 1, the tree is unbalanced.",
          ),
          l2(
            "lca",
            "LCA (Lowest Common Ancestor)",
            "Trees",
            "If the current node is p or q, return it. Combine left and right answers: if both sides return a node, this is the LCA.",
            "Distance between nodes, ancestor queries, BST LCA via values.",
            "O(n)",
            "O(h)",
            "Find the lowest node that has both 1 and 7 as descendants.",
          ),
          l2(
            "path-sum",
            "Path Sum Patterns",
            "Trees",
            "Carry a running remainder down the path. At a leaf, check if the remainder is zero. Variants: any path, all paths, max path.",
            "Root-to-leaf targets, path listing, binary-tree maximum path sum.",
            "O(n)",
            "O(h)",
            "Does any root-to-leaf path sum to 9?",
          ),
        ],
      },
      {
        id: "bst",
        title: "Binary Search Tree",
        emoji: "08",
        blurb: "Validation, insert/delete, kth smallest.",
        patterns: [
          l2(
            "bst-validation",
            "BST validation",
            "BST",
            "Every node must lie in a (low, high) window. Left child gets (low, node), right gets (node, high). Not just left < node < right at one node.",
            "Recover BST, serialize checks, interview classic.",
            "O(n)",
            "O(h)",
            "Walk a tree with bounds; a misplaced 3 fails the window.",
          ),
          l2(
            "bst-insert-delete",
            "Insert / Delete",
            "BST",
            "Insert walks left/right until a null child. Delete has three cases: leaf, one child, two children (replace with inorder successor).",
            "BST maps, policy trees, interview mutations.",
            "O(h)",
            "O(h)",
            "Insert 5 into a BST, then delete a node with two children.",
          ),
          l2(
            "kth-smallest",
            "Kth smallest",
            "BST",
            "Inorder of a BST is sorted. Count down k as you visit; when k hits 0 you have the answer. Morris or stack avoids extra arrays.",
            "Order statistics, median in BST, kth largest (reverse inorder).",
            "O(h + k)",
            "O(h)",
            "Inorder until the 3rd node.",
          ),
          l2(
            "inorder-logic",
            "Inorder-based logic",
            "BST",
            "Keep the previous inorder value. If it is not strictly increasing, the BST (or two swapped nodes) is broken.",
            "Recover two swapped nodes, min-diff between BST nodes, range sum.",
            "O(n)",
            "O(h)",
            "Track previous as you inorder; gaps and inversions show up immediately.",
          ),
        ],
      },
      {
        id: "heap",
        title: "Heap / Priority Queue",
        emoji: "09",
        blurb: "Top K, kth largest, merge k lists.",
        patterns: [
          l2(
            "top-k",
            "Top K Elements",
            "Heap",
            "A min-heap of size k stores the best k so far. If a new value is larger than the heap min, replace it. The heap is the answer.",
            "Top k frequent, k closest points, streaming top k.",
            "O(n log k)",
            "O(k)",
            "Keep a size-3 min-heap over a stream of numbers.",
          ),
          l2(
            "kth-largest",
            "Kth Largest / Smallest",
            "Heap",
            "Same heap of size k: after the whole array, the root is the kth largest. Quickselect is average O(n) but heaps are simpler.",
            "Kth in a stream, running median (two heaps — later).",
            "O(n log k)",
            "O(k)",
            "Find the 2nd largest using a min-heap of size 2.",
          ),
          l2(
            "merge-k-lists",
            "Merge K Sorted Lists",
            "Heap",
            "Push the head of each list into a min-heap. Pop the smallest, push its next. Repeat. K pointers, one heap.",
            "Merge k sorted arrays, smallest range covering k lists.",
            "O(n log k)",
            "O(k)",
            "Merge three sorted streams with a heap of heads.",
          ),
          l2(
            "heap-hashmap",
            "Heap + HashMap",
            "Heap",
            "The map stores frequency (or last index). The heap orders by that value. When a count changes, push a fresh pair; stale heap entries are skipped.",
            "Top k frequent words, lazy deletion, task scheduler.",
            "O(n log k)",
            "O(n)",
            "Count letters, then heap by frequency.",
          ),
        ],
      },
      {
        id: "greedy",
        title: "Greedy Patterns",
        emoji: "10",
        blurb: "Activity selection, intervals, platforms, jobs.",
        patterns: [
          l2(
            "activity-selection",
            "Activity Selection",
            "Greedy",
            "Sort by finish time. Always take the next activity that starts after the last chosen finish. Earliest-finish is optimal.",
            "Scheduling without overlap, maximum meetings.",
            "O(n log n)",
            "O(1)",
            "Pick a maximum set of non-overlapping meetings.",
          ),
          l2(
            "interval-scheduling",
            "Interval Scheduling",
            "Greedy",
            "Same family as activity selection. Sort, scan, take if compatible. Weighted version needs DP — not greedy.",
            "Calendar conflicts, CPU intervals, meeting rooms II is a variant.",
            "O(n log n)",
            "O(n)",
            "Schedule compatible intervals after sorting by end.",
          ),
          l2(
            "merge-intervals",
            "Merge Intervals",
            "Greedy",
            "Sort by start. If the next interval overlaps the current end, extend the end; otherwise push a new block.",
            "Calendar merge, insert interval, employee free time.",
            "O(n log n)",
            "O(n)",
            "Merge overlapping ranges into disjoint ones.",
          ),
          l2(
            "minimum-platforms",
            "Minimum Platforms",
            "Greedy",
            "Sort arrivals and departures separately. Sweep a timeline: +1 on arrival, −1 on departure. The max concurrent trains is the platform count.",
            "Meeting rooms II, minimum gates, concurrent users.",
            "O(n log n)",
            "O(1)",
            "Count how many trains overlap at the station.",
          ),
          l2(
            "job-sequencing",
            "Job Sequencing",
            "Greedy",
            "Sort jobs by profit. Place each job in the latest free slot before its deadline. A slot array (or DSU) holds the schedule.",
            "Deadline profit maximization, unit-time jobs.",
            "O(n log n + n·d)",
            "O(d)",
            "Fill deadline slots with the most profitable jobs first.",
          ),
        ],
      },
      {
        id: "graph-basics",
        title: "Graph Basics",
        emoji: "11",
        blurb: "BFS/DFS, components, cycles, bipartite.",
        patterns: [
          l2(
            "graph-bfs-dfs",
            "BFS / DFS",
            "Graph",
            "DFS uses a stack (or recursion); BFS uses a queue. Mark visited so you do not loop. Same graph, different order.",
            "Traversal, flood fill, shortest path in unweighted graphs (BFS).",
            "O(V + E)",
            "O(V)",
            "Walk a small undirected graph from A with both orders.",
          ),
          l2(
            "connected-components",
            "Connected Components",
            "Graph",
            "For each unvisited node, start a DFS/BFS. That walk is one component. Count how many times you start.",
            "Number of islands, friend circles, provinces.",
            "O(V + E)",
            "O(V)",
            "Count disconnected blobs in a graph.",
          ),
          l2(
            "graph-cycle",
            "Cycle Detection",
            "Graph",
            "Undirected: a visited neighbor that is not your parent is a cycle. Directed: a node in the recursion stack (gray) is a back edge.",
            "Course schedule, deadlock, undirected loop check.",
            "O(V + E)",
            "O(V)",
            "DFS coloring finds a back edge in a directed graph.",
          ),
          l2(
            "bipartite",
            "Bipartite Graph",
            "Graph",
            "Color nodes with two colors along BFS/DFS. If an edge joins two nodes of the same color, it is not bipartite.",
            "Odd-cycle test, graph coloring, matching setups.",
            "O(V + E)",
            "O(V)",
            "2-color a graph; a triangle fails.",
          ),
        ],
      },
      {
        id: "backtracking-full",
        title: "Backtracking (Full)",
        emoji: "12",
        blurb: "Subsets, permutations, N-Queens, Sudoku.",
        patterns: [
          l2(
            "subsets",
            "Subsets",
            "Backtracking",
            "At each index: pick or skip. Record the path at every node (or only at leaves). That generates the power set.",
            "Subsets II with duplicates, subset-sum decisions.",
            "O(2^n)",
            "O(n)",
            "Build every subset of [1, 2, 3].",
          ),
          l2(
            "permutations",
            "Permutations",
            "Backtracking",
            "Swap or used[] marks. Place a unused number in the next slot, recurse, undo. n! leaves.",
            "Next permutation, unique perms with duplicates.",
            "O(n!)",
            "O(n)",
            "Generate all orders of [1, 2, 3].",
          ),
          l2(
            "combination-sum",
            "Combination Sum",
            "Backtracking",
            "You may reuse a candidate (stay on i) or move to i+1. Subtract from the target; hit 0 to record; go negative to prune.",
            "Coin combinations, combination sum II (no reuse).",
            "O(n^{T/min})",
            "O(T)",
            "Make target 7 from [2, 3, 6, 7].",
          ),
          l2(
            "n-queens",
            "N-Queens",
            "Backtracking",
            "Place one queen per row. Track used columns and both diagonals. Undo on the way back.",
            "Constraint boards, hash-based diagonal keys.",
            "O(n!)",
            "O(n)",
            "Place 4 queens so none attack.",
          ),
          l2(
            "sudoku-solver",
            "Sudoku Solver",
            "Backtracking",
            "Find an empty cell, try 1–9 that respects row, column, and box, recurse. If stuck, undo. Mini 4×4 shows the same idea.",
            "Constraint satisfaction, dancing links (advanced).",
            "O(9^k)",
            "O(k)",
            "Fill a 4×4 Sudoku by trying digits and backtracking.",
          ),
        ],
      },
    ],
  },
  {
    id: 3,
    title: "Product Company",
    subtitle: "Make-or-break for 14–20 LPA offers",
    band: "14–20 LPA",
    warning: "These are make-or-break for top offers.",
    ready: true,
    groups: [
      {
        id: "dp-core",
        title: "Dynamic Programming (CORE)",
        emoji: "13",
        blurb: "1D/2D DP: Fibonacci, knapsack, LCS, grid.",
        patterns: [
          l3(
            "1d-dp",
            "1D DP",
            "DP",
            "Define dp[i] as the answer using the first i items (or ending at i). Fill left to right from smaller subproblems.",
            "Linear recurrences: climbing stairs, rob houses, max sum with a local choice.",
            "O(n)",
            "O(n) or O(1)",
            "Fill dp[i] = dp[i-1] + dp[i-2] for climbing n stairs.",
          ),
          l3(
            "fibonacci-pattern",
            "Fibonacci pattern",
            "DP",
            "The next value is the sum of the previous two. Cache those two (or the whole row) instead of branching recursion.",
            "Climbing stairs, tiling, decode ways — anything that splits into take-1 / take-2.",
            "O(n)",
            "O(1)",
            "Compute F(6) by rolling 0, 1, 1, 2, 3, 5, 8.",
          ),
          l3(
            "house-robber",
            "House Robber",
            "DP",
            "At house i: skip it (keep dp[i-1]) or rob it (nums[i] + dp[i-2]). Adjacent houses cannot both be robbed.",
            "Max sum with no two adjacent picks. Circular variant skips first or last.",
            "O(n)",
            "O(1)",
            "Rob [2, 7, 9, 3] without taking neighbors.",
          ),
          l3(
            "coin-change",
            "Coin Change",
            "DP",
            "dp[x] = min coins to make amount x. For each coin, dp[x] = min(dp[x], 1 + dp[x-coin]). Unbounded knapsack on a 1D row.",
            "Fewest coins, number of combinations, unbounded item reuse.",
            "O(n * amount)",
            "O(amount)",
            "Make 11 with coins [1, 2, 5].",
          ),
          l3(
            "2d-dp",
            "2D DP",
            "DP",
            "dp[i][j] depends on a constant neighborhood — usually left, up, or diagonal. Fill row by row.",
            "Two sequences, grids, or (item, capacity) tables.",
            "O(n * m)",
            "O(n * m)",
            "Unique paths in a 3x3 grid: only right and down.",
          ),
          l3(
            "knapsack",
            "Knapsack (0/1 + Unbounded)",
            "DP",
            "0/1: each item at most once — iterate capacity backward. Unbounded: forward, so the same item can be reused.",
            "Capacity + values/weights. Coin change is unbounded knapsack.",
            "O(n * W)",
            "O(W)",
            "Items (w,v) = (2,3), (3,4), (4,5) into capacity 5.",
          ),
          l3(
            "lcs-lps",
            "LCS / LPS",
            "DP",
            "LCS: if chars match, 1 + diagonal, else max(left, up). LPS of s is LCS(s, reverse(s)).",
            "Diffs, palindromic subsequences, shortest supersequence.",
            "O(n * m)",
            "O(n * m)",
            "LCS of \"abc\" and \"ac\" is \"ac\".",
          ),
          l3(
            "grid-dp",
            "Grid DP",
            "DP",
            "dp[r][c] = grid[r][c] + min (or max) of allowed previous cells, usually up and left. Obstacles block a cell.",
            "Min path sum, unique paths, dungeon game, cherry pickup (advanced).",
            "O(n * m)",
            "O(n * m)",
            "Min path sum on a 3x3 cost grid.",
          ),
        ],
      },
      {
        id: "dp-subseq",
        title: "DP on Subsequences",
        emoji: "14",
        blurb: "LIS, subset sum, partition.",
        patterns: [
          l3(
            "lis",
            "LIS",
            "DP",
            "dp[i] = 1 + max dp[j] for j < i and a[j] < a[i]. Patience-sorting tails array gives O(n log n).",
            "Longest increasing / decreasing, Russian doll envelopes after sort.",
            "O(n^2) or O(n log n)",
            "O(n)",
            "LIS of [10, 9, 2, 5, 3, 7] is 2, 5, 7 or 2, 3, 7.",
          ),
          l3(
            "subset-sum",
            "Subset Sum",
            "DP",
            "Boolean knapsack: can[t] becomes true if can[t] or can[t-a[i]] was true. Fill backward for 0/1.",
            "Target sum, partition, closest subset.",
            "O(n * T)",
            "O(T)",
            "Can [2, 3, 7] make 5? Yes: 2+3.",
          ),
          l3(
            "partition-equal",
            "Partition Equal Subset",
            "DP",
            "If total sum is odd, impossible. Otherwise subset-sum the half. Same 0/1 knapsack boolean row.",
            "Equal-sum partition, last stone weight II.",
            "O(n * sum/2)",
            "O(sum)",
            "Split [1, 5, 11, 5] into two subsets of sum 11.",
          ),
        ],
      },
      {
        id: "dp-strings",
        title: "DP on Strings",
        emoji: "15",
        blurb: "Edit distance, wildcard, palindrome partition.",
        patterns: [
          l3(
            "edit-distance",
            "Edit Distance",
            "DP",
            "dp[i][j] = min insert, delete, replace to turn s[0..i) into t[0..j). Match is free on the diagonal.",
            "Spellcheck, DNA alignment, fuzzy match.",
            "O(n * m)",
            "O(n * m)",
            "Turn \"cat\" into \"cut\" with one replace.",
          ),
          l3(
            "wildcard-matching",
            "Wildcard Matching",
            "DP",
            "? matches one char. * matches empty or more — dp[i][j] from left (eat s) or up (eat *).",
            "Glob patterns, regex-lite without backtracking blow-up.",
            "O(n * m)",
            "O(n * m)",
            "Does \"a*\" match \"aa\"?",
          ),
          l3(
            "palindrome-partition",
            "Palindrome Partitioning",
            "DP",
            "Precompute pal[l][r]. Then cuts[i] = min cuts[j]+1 when s[j..i] is a palindrome. Backtracking lists the partitions.",
            "Min cuts, all palindrome partitions.",
            "O(n^2)",
            "O(n^2)",
            "\"aab\" splits as \"aa\" | \"b\" with one cut.",
          ),
        ],
      },
      {
        id: "advanced-graphs",
        title: "Advanced Graph Patterns",
        emoji: "16",
        blurb: "Topo, Dijkstra, Bellman Ford, Floyd, MST.",
        patterns: [
          l3(
            "topo-sort",
            "Topological Sort",
            "Graph",
            "Kahn: queue nodes with indegree 0, peel outgoing edges. DFS: finish times reverse to a valid order. Only DAGs.",
            "Course schedule, build order, alien dictionary.",
            "O(V + E)",
            "O(V)",
            "Order a DAG: A before B and D, both before C.",
          ),
          l3(
            "dijkstra",
            "Dijkstra",
            "Graph",
            "Non-negative weights. Pop the closest unsettled node, relax its edges. A min-heap keeps the frontier.",
            "Shortest path on maps, weighted grids without negative edges.",
            "O((V + E) log V)",
            "O(V)",
            "Shortest path from A on a tiny weighted graph.",
          ),
          l3(
            "bellman-ford",
            "Bellman Ford",
            "Graph",
            "Relax every edge V-1 times. A V-th pass that still relaxes means a negative cycle reachable from the source.",
            "Negative weights, cheapest flight with k stops (a bounded Ford).",
            "O(V * E)",
            "O(V)",
            "Relax edges including a negative one; detect a cycle if it keeps dropping.",
          ),
          l3(
            "floyd-warshall",
            "Floyd Warshall",
            "Graph",
            "Triple loop: for each mid k, dist[i][j] = min(dist[i][j], dist[i][k] + dist[k][j]). All-pairs.",
            "Dense graphs, transitive closure, small V.",
            "O(V^3)",
            "O(V^2)",
            "All-pairs distances on 3 nodes.",
          ),
          l3(
            "mst",
            "Minimum Spanning Tree (Prim / Kruskal)",
            "Graph",
            "Prim grows from a node by cheapest cut edge. Kruskal sorts edges and adds if DSU says no cycle. Same tree weight.",
            "Connect all cities with min cable, clustering.",
            "O(E log V)",
            "O(V)",
            "Connect four nodes with the three cheapest non-cycle edges.",
          ),
        ],
      },
      {
        id: "dsu",
        title: "Union Find (DSU)",
        emoji: "17",
        blurb: "Cycles, components, Kruskal.",
        patterns: [
          l3(
            "dsu-cycle",
            "Cycle detection",
            "DSU",
            "For each undirected edge, if find(u)==find(v) it closes a cycle. Else union. Path compression + union by rank.",
            "Redundant connection, Kruskal skip, undirected cycle.",
            "O(alpha(n))",
            "O(n)",
            "Edges (1-2), (2-3), (1-3) — the third is a cycle.",
          ),
          l3(
            "dsu-components",
            "Number of components",
            "DSU",
            "Start with n components. Each successful union decrements the count by one.",
            "Number of provinces, islands with union, accounts merge.",
            "O(n + m alpha(n))",
            "O(n)",
            "Four nodes, two unions → three components.",
          ),
          l3(
            "kruskal",
            "Kruskal’s algorithm",
            "DSU",
            "Sort edges by weight. Add if the endpoints are in different sets. Stop at n-1 edges.",
            "MST, bottleneck paths, clustering by skipping longest edges.",
            "O(E log E)",
            "O(V)",
            "Same MST as Prim, built by sorted edges + DSU.",
          ),
        ],
      },
      {
        id: "bits",
        title: "Bit Manipulation",
        emoji: "18",
        blurb: "XOR, missing numbers, bit masks.",
        patterns: [
          l3(
            "xor-tricks",
            "XOR tricks",
            "Bits",
            "x^x = 0, x^0 = x, XOR is associative. Pairing cancels duplicates; the leftover is the unique (or swapped) value.",
            "Single number, missing XOR, swap without temp.",
            "O(n)",
            "O(1)",
            "XOR [2, 3, 2, 4, 4] leaves 3.",
          ),
          l3(
            "missing-number",
            "Single / Double missing number",
            "Bits",
            "XOR 1..n with all array values — duplicates cancel, missing (or extra) remains. Two missings: split by a differing bit.",
            "Find the lost index, two unique numbers.",
            "O(n)",
            "O(1)",
            "n=4, array [1, 2, 4] — XOR finds 3.",
          ),
          l3(
            "bit-masking",
            "Bit masking",
            "Bits",
            "An int stores a set: test (mask>>i)&1, set mask|1<<i, clear mask&~(1<<i). DP on subsets loops masks.",
            "TSP DP, assignment, small-n set problems, flags.",
            "O(1) per op",
            "O(1)",
            "Mask 5 is bits 101 — elements 0 and 2.",
          ),
          l3(
            "subsets-bits",
            "Subsets using bits",
            "Bits",
            "For mask in 0..(1<<n)-1, bit i on means a[i] is in the subset. 2^n enumerations without recursion.",
            "Enumerate subsets when n <= 20.",
            "O(n * 2^n)",
            "O(1)",
            "All subsets of [A, B, C] via masks 0..7.",
          ),
        ],
      },
      {
        id: "trie",
        title: "Trie (Prefix Tree)",
        emoji: "19",
        blurb: "Insert, search, word search, autocomplete.",
        patterns: [
          l3(
            "trie-insert-search",
            "Insert / Search",
            "Trie",
            "Each edge is a character. Insert walks/creates children; search follows. A terminal flag marks a complete word.",
            "Dictionary, prefix checks, replace words.",
            "O(L)",
            "O(ALPHABET * nodes)",
            "Insert CAT, search CAT vs CAP.",
          ),
          l3(
            "word-search",
            "Word Search",
            "Trie",
            "Board DFS + trie (or a set of words). Prune when the path is not a trie prefix. Mark cells visited, then undo.",
            "Boggle, word search II (many words).",
            "O(m n * 4^L)",
            "O(L)",
            "Find CAT on a tiny letter grid.",
          ),
          l3(
            "autocomplete",
            "Auto-complete",
            "Trie",
            "Walk the prefix to a node, then DFS/BFS its subtree to collect terminals — the suggestions.",
            "Search box, ranked by frequency at nodes.",
            "O(P + hits)",
            "O(nodes)",
            "Prefix \"ca\" suggests cat and car.",
          ),
        ],
      },
      {
        id: "advanced",
        title: "Advanced Patterns",
        emoji: "20",
        blurb: "Meet in the middle, window+DP, binary lifting, Mo’s.",
        patterns: [
          l3(
            "meet-in-middle",
            "Meet in the Middle",
            "Advanced",
            "Split n into two halves, enumerate 2^{n/2} subset sums each, then two-pointer / binary search the target pair.",
            "n around 40, subset-sum too big for 2^n, too sparse for DP on T.",
            "O(2^{n/2} n)",
            "O(2^{n/2})",
            "Target 10 from [2, 4, 5, 6] via two halves.",
          ),
          l3(
            "window-dp",
            "Sliding Window + DP",
            "Advanced",
            "dp[i] uses a max/min over a window of previous states. A deque keeps candidates monotonic so each index enters/leaves once.",
            "Jump game VI, constrained subsequence, sliding window maximum as a building block.",
            "O(n)",
            "O(n)",
            "dp[i] = a[i] + max(dp[i-k..i-1]) with k=2.",
          ),
          l3(
            "binary-lifting",
            "Binary Lifting",
            "Advanced",
            "up[i][k] = 2^k-th ancestor of i. Build from k=0 (parent). LCA / k-th ancestor jumps by bits of the distance.",
            "LCA on trees, kth ancestor queries, path aggregates.",
            "O(n log n) build, O(log n) query",
            "O(n log n)",
            "Jump from a leaf toward the root by 1, 2, 4…",
          ),
          l3(
            "mos-algorithm",
            "Mo’s Algorithm",
            "Advanced",
            "Offline queries. Sort by block of L, then R. Add/remove endpoints while walking from the previous [L,R] to the next.",
            "Many range queries where you can add/remove an index in O(1) or O(log n).",
            "O((n + q) * sqrt(n) * F)",
            "O(n)",
            "Answer two range-frequency queries by moving L and R.",
          ),
        ],
      },
    ],
  },
];

export function allPatterns(): Pattern[] {
  return levels.flatMap((level) =>
    level.groups.flatMap((group) => group.patterns),
  );
}

export function getPattern(slug: string): Pattern | undefined {
  return allPatterns().find((p) => p.slug === slug);
}

export function getLevel(id: number): Level | undefined {
  return levels.find((l) => l.id === id);
}

export function getGroupByPattern(slug: string) {
  for (const level of levels) {
    for (const group of level.groups) {
      if (group.patterns.some((p) => p.slug === slug)) {
        return { level, group };
      }
    }
  }
  return undefined;
}
